version: '3.8'

networks:
  soil-net:
    external: true

volumes:
  postgres-data:

services:
  database:
    build: .docker/postgres
    image: postgres:16
    container_name: database-postgres
    restart: always
    shm_size: 128mb
    networks:
      - soil-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
